server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/JEBOARD
    username: root
    password: tortue1024
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.project.ecommerce.dto


#application.properties
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3306/JEBOARD
#spring.datasource.username=root
#spring.datasource.password=tortue1024
